name: Subdomain Takeover Hunt

on:
  push:
    branches: [master]

jobs:
  takeover-hunt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies & subjack
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl jq
          go install github.com/haccer/subjack@latest
          cp $(go env GOPATH)/bin/subjack ./subjack

      - name: Download domain list & run subjack
        run: |
          mkdir -p results
          curl -s "https://raw.githubusercontent.com/z0rs/SubHunt/refs/heads/master/results/mobile-resolved.txt" \
            | awk '{print $1}' | sort -u > results/domains.txt

          ./subjack -w results/domains.txt -t 50 -timeout 10 -ssl -v -o results/results.txt

      - name: Commit & Push Results
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git add results/
          git commit -m "🏴‍☠️ Takeover Hunt Update" --no-verify || echo "No changes to commit"
          git push origin master || true
