name: Subdomain Takeover Hunt

on:
  push:
    branches: [master]

jobs:
  takeover-hunt:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies & subzy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          go install github.com/PentestPad/subzy@latest
          cp $(go env GOPATH)/bin/subzy ./subzy

      - name: Download domain list & run subzy
        run: |
          mkdir -p results
          curl -s "https://raw.githubusercontent.com/z0rs/Hunting/refs/heads/master/results/takeover-candidates.txt" \
            | awk '{print $1}' | sort -u > results/domains.txt

          subzy run --targets results/domains.txt --concurrency 50 --hide_fails --timeout 10 --vuln --output results/takeover.json

      - name: Commit & Push Results
        run: |
          git config --global user.email "${{ secrets.EMAIL_ADDRESS }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git add results/
          git commit -m "🏴‍☠️ Takeover Hunt Update" --no-verify || echo "No changes to commit"
          git push origin master || true
